block-list-secret-scan: []
branch: main
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
mask: []
quiet: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-results-upload: true
skip-check:
# Disabled CKV_TF_1 as there is a risk with using tags, but the readibility is better with tags vs commit hash
# https://docs.prismacloud.io/en/enterprise-edition/policy-reference/supply-chain-policies/terraform-policies/ensure-terraform-module-sources-use-git-url-with-commit-hash-revision
- CKV_TF_1
# Disabled CKV_TF_2 as we are using the terraform standard for module version
- CKV_TF_2
# Disabled CKV_AWS_158 as we currently don't encrypt the CloudWatch logs and it's impact is hard to determine (needs to be enabled in the future)
# https://docs.prismacloud.io/en/enterprise-edition/policy-reference/aws-policies/aws-general-policies/ensure-that-cloudwatch-log-group-is-encrypted-by-kms
- CKV_AWS_158
# Disabled CKV_AWS_260 to allow port 80 connections to the LB, as the listener redirects requests from 80 to 443
# https://docs.prismacloud.io/en/enterprise-edition/policy-reference/aws-policies/aws-networking-policies/ensure-aws-security-groups-do-not-allow-ingress-from-00000-to-port-80
- CKV_AWS_260
# Disabled CKV_AWS_333 as we are currently running our services in a public subnet and in order to retrieve secrets & docker images we need a Public IP
# https://docs.prismacloud.io/en/enterprise-edition/policy-reference/aws-policies/aws-logging-policies/bc-aws-333
- CKV_AWS_333
summary-position: top
